#!/bin/bash

echo '*****************************************************************'
sudo journalctl --no-hostname -eu rainbowfilly | tail -n 25 | cut -f 2,3,5- -d ' '
echo "$(date +%d' '%H:%M:%S) *****************************************************"